# Generated by Django 3.2.12 on 2022-04-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='departments',
            field=models.ManyToManyField(related_name='departments', to='hospitalapp.Department'),
        ),
    ]
