# Generated by Django 3.2.12 on 2022-04-27 09:15

from django.db import migrations


def create_medicines(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Medicine = apps.get_model('hospitalapp', 'Medicine')
    Medicine.objects.using(db_alias).bulk_create([
        Medicine(active_substance='levothyroxine', medicine_strenght='10',
                 contraindications='Cold symptoms', title='Synthroid'),
        Medicine(active_substance='rosuvastatin', medicine_strenght='20',
                 contraindications='Joint pain', title='Crestor'),
        Medicine(active_substance='albuterol', medicine_strenght='40',
                 contraindications='Diarrhea', title='Ventolin HFA'),
        Medicine(active_substance='infliximab', medicine_strenght='50',
                 contraindications='Forgetfulness', title='Remicade'),
        Medicine(active_substance='esomeprazole', medicine_strenght='30',
                 contraindications='Diarrhea', title='Nexium'),
        Medicine(active_substance='etanercept', medicine_strenght='10',
                 contraindications='Heartburn', title='Enbrel'),
        Medicine(active_substance='fluticasone', medicine_strenght='40',
                 contraindications='Cold symptoms', title='Atorvastatin'),
        Medicine(active_substance='succinate', medicine_strenght='10',
                 contraindications='Urinary tract infection (UTI)', title='Metoprolol'),
        Medicine(active_substance='levothyroxine', medicine_strenght='20',
                 contraindications='Heartburn', title='Levothyroxine'),


    ])


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_auto_20220426_1458'),
    ]

    operations = [
        migrations.RunPython(create_medicines),
    ]
