# Generated by Django 3.2.12 on 2022-04-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0005_dose_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dose',
            name='application_method',
            field=models.SmallIntegerField(choices=[(1, 'Orally'), (2, 'Intravenously'), (3, 'Intramuscularly'), (4, 'Under the tongue'), (5, 'Other')], default=1),
        ),
    ]
