APPLICATION_METHOD_ORALLY = 'orally'
APPLICATION_METHOD_IV = 'intravenously'
APPLICATION_METHOD_IM = 'intramuscularly'
APPLICATION_METHOD_SL = 'sublingually'
APPLICATION_METHOD_OTHER = 'other'

APPLICATION_METHOD_CHOICES = [
    (APPLICATION_METHOD_ORALLY, 'Orally'),
    (APPLICATION_METHOD_IV, 'Intravenously'),
    (APPLICATION_METHOD_IM, 'Intramuscularly'),
    (APPLICATION_METHOD_SL, 'Under the tongue'),
    (APPLICATION_METHOD_OTHER, 'Other'),
]
