APPLICATION_METHOD_ORALLY = 1
APPLICATION_METHOD_IV = 2
APPLICATION_METHOD_IM = 3
APPLICATION_METHOD_SL = 4
APPLICATION_METHOD_OTHER = 5

APPLICATION_METHOD_CHOICES = [
    (APPLICATION_METHOD_ORALLY, 'Orally'),
    (APPLICATION_METHOD_IV, 'Intravenously'),
    (APPLICATION_METHOD_IM, 'Intramuscularly'),
    (APPLICATION_METHOD_SL, 'Under the tongue'),
    (APPLICATION_METHOD_OTHER, 'Other'),
]
